CREATE TABLE IF NOT EXISTS expenses_execution (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year_and_month                  VARCHAR(10)     NOT NULL,
    superior_organ_code             INTEGER         NOT NULL,
    superior_organ_name             VARCHAR(255),
    subordinated_organ_code         INTEGER         NOT NULL,
    subordinated_organ_name         VARCHAR(255),
    management_unit_code            INTEGER         NOT NULL,
    management_unit_name            VARCHAR(255),
    management_code                 INTEGER         NOT NULL,
    management_name                 VARCHAR(255),
    action_code                     INTEGER         NOT NULL,
    action_name                     VARCHAR(255),
    budget_plan_code                INTEGER         NOT NULL DEFAULT 0,
    budget_plan_name                VARCHAR(255),
    federative_unit                 VARCHAR(10),
    municipality                    VARCHAR(255),
    author_amendament_code          INTEGER         NOT NULL DEFAULT 0,
    author_amendament_name          VARCHAR(255),
    economic_category_code          INTEGER         NOT NULL,
    economic_category_name          VARCHAR(255),
    expense_group_code              INTEGER         NOT NULL,
    expense_group_name              VARCHAR(255),
    expense_category_code           INTEGER         NOT NULL,
    expense_category_name           VARCHAR(255),
    expense_modality_code           INTEGER         NOT NULL DEFAULT 0,
    expense_modality_name           VARCHAR(255),
    committed_value_brl             NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    liquidated_value_brl            NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    paid_value_brl                  NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    registered_payables_amount_brl  NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    canceled_payables_amount_brl    NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    paid_payables_amount_brl        NUMERIC(18, 2)  NOT NULL DEFAULT 0,
    inserted_at                     TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMP       NOT NULL DEFAULT NOW(),

    UNIQUE (
        year_and_month,
        management_unit_code,
        management_code,
        action_code,
        budget_plan_code,
        expense_group_code,
        expense_category_code,
        expense_modality_code,
        federative_unit,
        municipality,
        author_amendament_code
    )
);

CREATE INDEX idx_expenses_execution_year_and_month     ON expenses_execution(year_and_month);
CREATE INDEX idx_expenses_execution_management_unit    ON expenses_execution(management_unit_code);
CREATE INDEX idx_expenses_execution_management_code    ON expenses_execution(management_code);
CREATE INDEX idx_expenses_execution_action_code        ON expenses_execution(action_code);
